/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { SimpleERC20__factory } from "./SimpleERC20__factory";
export { SimpleERC721__factory } from "./SimpleERC721__factory";
